# Default values for legend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  GITLAB_URL: "gitlab.com"
  LEGEND_HOST: "legend.arsalan.io"
  GITLAB_OAUTH_CLIENT_ID: "38ad9d7f67567437ec3a637281021f1991d8a4c0e5705347cf81cbba48f54091"
  GITLAB_OAUTH_SECRET: "bb05c6f6f9281c80e20c1688dcfdcd9d043455bd9692f4fb1b5141d0527c3212"

clusterdns: "svc.cluster.local"

sdlc:
  repository: "finos/legend-sdlc-server"
  tag: "0.45.0"
  port: "7070"
  type: ClusterIP
  env:
  pullPolicy: IfNotPresent

engine:
  repository: "finos/legend-engine-server"
  tag: "2.39.0"
  port: "6060"
  type: ClusterIP
  env:
  pullPolicy: IfNotPresent

studio:
  repository: "finos/legend-studio"
  tag: "0.2.5"
  port: "7070"
  type: ClusterIP
  env: "8080"
  pullPolicy: IfNotPresent

mongo:
  repository: "mongo"
  tag: "4.0"
  port: 27017
  type: ClusterIP
  env:
    MONGO_USER: "admin"
    MONGO_PASSWORD: "admin"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
