apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "legend.fullname" . }}
  labels:
    {{- include "legend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.env.LEGEND_HOST }}
    http:
      paths:
      - path: /studio
        pathType: Prefix
        backend:
          service:
            name: {{ include "legend.fullname" . }}-studio
            port:
              number: {{ .Values.studio.port }}
      - path: /sdlc
        pathType: Prefix
        backend:
          service:
            name: {{ include "legend.fullname" . }}-sdlc
            port:
              number: {{ .Values.sdlc.port }}
      - path: /engine
        pathType: Prefix
        backend:
          service:
            name: {{ include "legend.fullname" . }}-engine
            port:
              number: {{ .Values.engine.port }}